layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: uditha.maduranga.95
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: uditha-maduranga
  # mastodon: your_username
  medium: maduranga95
  stackoverflow: uditha-maduranga
  # telegram: your_username
  twitter: maduranga95
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    web_url: https://www.python.org/
    image_url: https://www.python.org/static/img/python-logo.png

  - name: Vue.js
    web_url: https://vuejs.org/
    image_url: https://miro.medium.com/max/700/1*OrjCKmou1jT4It5so5gvOA.jpeg

  - name: Angular
    web_url: https://angular.io/
    image_url: https://cdn.worldvectorlogo.com/logos/angular-icon.svg

  - name: Keras
    web_url: https://keras.io/
    image_url: https://upload.wikimedia.org/wikipedia/commons/c/c9/Keras_Logo.jpg

  - name: AWS
    web_url: https://aws.amazon.com/
    image_url: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png
